### CREATE GROUP

POST http://127.0.0.1:8000/rpc
Content-Type: application/json


{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "CREATE_GROUP",
  "params": {
      "tribeGroupId": "1234...abch",
      "tribeAddress": "0x1235...",
      "name": "NFT Discuss 02",
      "description": "Discuss how NFT works...",
      "address": "0xa1b2...",
      "username": "@cryptolxf",
      "expires": 1940827381,
      "role": 0,
      "owner": true
  }
}

### REMOVE GROUOP

POST http://127.0.0.1:8000/rpc
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "REMOVE_GROUP",
  "params": {
      "tribeGroupId": "1234...abcg",
      "tribeAddress": "0x1235...",
      "address": "0xa1b2...",
      "username":"@cryptolxf"
  }
}

### ADD MEMBER
POST http://127.0.0.1:8000/rpc
Content-Type: application/json

{
"id": 1,
"jsonrpc": "2.0",
"method": "ADD_MEMBER",
"params": {
      "tribeGroupId": "1234...abce",
      "tribeAddress": "0x1234...",
      "address": "0xa1b2...",
      "username": "@tigersnow",
      "role": 0,
      "expires": 6000000000,
      "owner": false
  }
}

### UPDATE MEMBER
POST http://127.0.0.1:8000/rpc
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "UPDATE_MEMBER",
  "params": {
    "tribeGroupId": "1234...abce",
    "tribeAddress": "0x1234...",
    "address": "0xa1b2...",
    "username": "@tigersnow",
    "role": 1,
    "expires": 1640995200,
    "owner": false
  }
}

### Remove MEMBER
POST http://127.0.0.1:8000/rpc
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "REMOVE_MEMBER",
  "params": {
    "tribeGroupId": "1234...abch",
    "tribeAddress": "0x1235...",
    "address": "0xa1b2...",
    "username": "@cryptolxf",
    "role": 1,
    "expires": 1640995200,
    "owner": false
  }
}


### notify member message
POST http://127.0.0.1:8000/rpc
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "NOTIFY_MEMBER",
  "params": {
    "tribeGroupId": "1234...abce",
    "tribeAddress": "0x1234...",
    "address": "0xa1b2...",
    "username": "@cryptolxf",
    "message": "Hi bob, please note ..."
  }
}

### notify group
POST http://127.0.0.1:8000/rpc
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "NOTIFY_GROUP",
  "params": {
    "tribeGroupId": "1234...abce",
    "message": "Hi everyone, please note ..."
  }
}